### ISSUE TITLE
out of range

### ISSUE THREAD

**Issue by sunny98452patel** [adars124/BulkCLI#2]
index out of range how to solve this let me know

**Comment by Bishad-Upadhyaya** [comment]
Could you please elaborate more about the issue? Maybe a link (url) of screenshot so that I can work on it.

**Comment by sunny98452patel** [comment]
I was trying to apply for the ipo for more than 10 accounts and it said
INDEX OUT OF RANGE




How can I apply for it having more than 10 accounts?
Please tell me how to solve this problem

**Comment by Bishad-Upadhyaya** [comment]
I have a solution, can you manually type the user information in the accounts.txt file once? And let me know. I was having the same issue, sometimes the file reader hallucinates for some reason.

**Comment by sunny98452patel** [comment]
I did by typing all the info in the account section but it said the same
error

Can u plz share ur number or call me 9845268037

???


Waiting for your reply

**Comment by Bishad-Upadhyaya** [comment]
I will text you in telegram if you have it

**Comment by sunny98452patel** [comment]
You please reply in messenger I have messaged u
